#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "ite209-pc-01.cs.umbc.edu";
$SERVER_PORT = 2756;
$COURSE_NAME = "CMCS313";
$AUTOGRADE_TIMEOUT = 0;
1;
